### PR TITLE
Make args a xicam namespace package.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
This makes `xicam.args` importable without breaking other `xicam` namespace packages.

```py
In [1]: import xicam.args                                                                                                                                                                     

In [2]: import xicam.catalog_viewer
```

**Comment by danielballan** [comment]
On Travis, the Python 3.7 Linux build passed, but it looks like the Windows build is broken for reasons unrelated to this PR.

**Comment by mrakitin** [comment]
I pushed some missing fixes. Tested locally, worked fine:
```
xicam               2.2.4+4.g1827825
xicam.CatalogViewer 0.1.0
xicam.core          2.2.4
xicam.gui           2.2.4+2.g91e238a
xicam.plugins       2.2.4
```

```py
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import xicam.args

In [2]: import xicam

In [3]: import xicam.catalog_viewer
QObject::startTimer: Timers can only be used with threads started with QThread


/Users/mrakitin/src/synchrotrons/xi-cam.gui/xicam/gui/cammart/packagemanager.py:157: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._store = yaml.load(f.read())




Thu Dec 12 12:56:05 2019 - __init__ - INFO - M - plugindirectories: /Users/mrakitin/Library/Caches/xicam/plugins /Library/Application Support/xicam/plugins /Users/mrakitin/src/synchrotrons/xi-cam.gui/xicam /Users/mrakitin/src/synchrotrons/xi-cam.gui/xicam /Users/mrakitin/anaconda3/envs/xicam-args/lib/python3.7/site-packages/xicam

In [4]:
```

**Comment by ihumphrey** [comment]
@danielballan Changes look good, wroked with @mrakitin to add some updates for versioneer and finding args through setup.

**Pull request merged**
